chore(infra): update ssh keys

diff --git a/.github/workflows/deploy-production.yml b/.github/workflows/deploy-production.yml
--- a/.github/workflows/deploy-production.yml
+++ b/.github/workflows/deploy-production.yml
@@ -42,7 +42,6 @@ jobs:
                     echo "TAG=${TAG}" >> $GITHUB_ENV
                     echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
                     IMAGE_TAG_KEY=${{ github.ref_name }}-image-tag-key
-                    aws secretsmanager delete-secret --secret-id "$IMAGE_TAG_KEY" --force-delete-without-recovery || true
                     aws secretsmanager create-secret --name "$IMAGE_TAG_KEY" --secret-string "$IMAGE_TAG"
                     echo "image-tag-key=$IMAGE_TAG_KEY" >> $GITHUB_OUTPUT
  
@@ -72,6 +71,12 @@ jobs:
                     file: Dockerfile
                     push: true
                     tags: ${{ env.IMAGE_TAG }}
+
+            - name: Clean up secrets
+              if: failure()
+              run: |
+                  # Clean up secrets
+                  aws secretsmanager delete-secret --secret-id "${{ steps.build-app.outputs.image-tag-key }}" --force-delete-without-recovery || true
 
     infra-provisioning:
         name: Provision AWS resources with terraform
@@ -107,7 +112,7 @@ jobs:
           TF_VAR_rdsconfig_db_name: ${{ secrets.TF_VAR_RDSCONFIG_DB_NAME }}
           TF_VAR_rdsconfig_username: ${{ secrets.TF_VAR_RDSCONFIG_USERNAME }}
           TF_VAR_rdsconfig_password: ${{ secrets.TF_VAR_RDSCONFIG_PASSWORD }} 
-          TF_VAR_ssh_private_key: ${{ secrets.TF_VAR_SSH_PRIVATE_KEY }}
+          TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_SSH_PUBLIC_KEY }}
           TF_VAR_ec2_ami: ${{ secrets.TF_VAR_EC2_AMI }}
 
         steps:
@@ -142,9 +147,16 @@ jobs:
               echo "ec2-ip=$(terraform output -raw eis_ec2_ip)" >> "$GITHUB_OUTPUT"
               value=$(terraform output -raw rds_endpoint)
               RDS_ENDPOINT_KEY=RDS_ENDPOINT_KEY-$(date +%s)-$RANDOM
-              aws secretsmanager delete-secret --secret-id "$RDS_ENDPOINT_KEY" --force-delete-without-recovery || true
               aws secretsmanager create-secret --name "$RDS_ENDPOINT_KEY" --secret-string "$value"
               echo "rds-endpoint-key=$RDS_ENDPOINT_KEY" >> "$GITHUB_OUTPUT"
+
+
+          - name: Clean up secrets
+            if: failure()
+            run: |
+                # Clean up secrets
+                aws secretsmanager delete-secret --secret-id "${{ steps.infra-provisioning.outputs.rds-endpoint-key }}" --force-delete-without-recovery || true
+
 
     deploy-app:
         name: Deploy docker app to EC2 instance
@@ -232,6 +244,9 @@ jobs:
                   echo "Deployment completed successfully"
                 EOF
 
+            - name: Clean up secrets
+              if: always()
+              run: |
                 # Clean up secrets
-                aws secretsmanager delete-secret --secret-id "$IMAGE_TAG_KEY" --force-delete-without-recovery
-                aws secretsmanager delete-secret --secret-id "$RDS_ENDPOINT_KEY" --force-delete-without-recovery
+                aws secretsmanager delete-secret --secret-id "${{ steps.build-app.outputs.image-tag-key }}" --force-delete-without-recovery || true
+                aws secretsmanager delete-secret --secret-id "${{ steps.infra-provisioning.outputs.rds-endpoint-key }}" --force-delete-without-recovery || true
